server:
  port: 6065

spring:
  application:
    name: ms-config-server

  cloud:
    config:
      server:
        git:
          uri: https://github.com/kevinraf/ACAD-ONECH.git # repositorio
          searchPaths:
            - config-data
          default-label: ONESAN

  security:
    user:
      name: daisqui
      password: onichan