spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: ms-compra
  profiles:
    active: development
  config:
    import: optional:configserver:http://daisqui:onichan@localhost:6065
